#swiftmailer:
#    url: '%env(MAILER_URL)%'
##    spool: { type: 'memory' }
#    stream_options:
#        ssl:
#            verify_peer: false
#            verify_peer_name: false
#            allow_self_signed: true

swiftmailer:
    transport: smtp
    host:      churipo.matmor.unam.mx
    username: swmail
    password: 
    encryption: tls
    port: 465
    auth-mode: login
    stream_options:
        ssl:
            verify_peer: false
            verify_peer_name: false
            allow_self_signed: true
