vich_uploader:
    db_driver: orm

    mappings:
        historial:
            uri_prefix: /documentos/historial
            upload_destination: '%kernel.project_dir%/public/documentos/historial'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        tarea:
            uri_prefix: /documentos/tarea
            upload_destination: '%kernel.project_dir%/public/documentos/tarea'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer